name = "LatinHypercubeSampling"
uuid = "a5e1c1ea-c99a-51d3-a14d-a9a37257b02d"
authors = ["Magnus Urquhart <magnus.urquhart@gmail.com>"]
version = "1.6.1"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
StatsBase = "^0.32"
julia = "^1.0"
